### PR TITLE
Add tasks generator (Unix only)

### PR DESCRIPTION
**Pull request by t1meshift**
Because I can lol

### CODE REVIEW

**Comment by FooBarrior** [comment]
>Because I can
Good.

> Unix only
Well, the whole solution is unix only

**Comment by FooBarrior** [comment]
The task is intended to be run by student -- by herself. The point is that the one downloading this task and running it is self-developing and improving the skills by building/running it, hacking through console, and maybe investigating the way it's done. It'll be very useful for student to do this way. Just like you done. But now you are the only person who can run makefiles, build C and use terminal shell. That's not what I as a teacher am aiming.

**Comment by FooBarrior** [comment]
I'd also suggest you close/delete your generator to promote others to use console and make. Better give'em a hand with doing this!

**Comment by t1meshift** [comment]
Give'em a hand? This is exactly what I have done and will do. They don't want to deal with Linux (what's sad but understandable) because of lack of knowledge about it. As far as I know, we hadn't been told even about how to use WSL. That's okay for me, the writer of that shell script, but not for newbies in systems other than Windows.
Also, someone has told that he will tell about GNU Make on lecture. :octocat:

**Comment by t1meshift** [comment]
And I don't think that I should delete my fork. Well, I could delete the generated file which I've added by mistake but the script works under Linux only, so I don't think the script in its current form can help someone except me.

**Pull request closed without merging**
